### PR TITLE
Invalided the REST connections to ES

### LINKED ISSUE #22: Made the extension work with new ElasticSearchDatastore
The ElasticsearchDatastore has been changed so that It allows connecting to elasticsearch via REST.  
The datastore returns 2 DataContext types when a connection is created: ElasticSearchDataContext
and ElasticSearchRestContext. Update the extension so that it accepts only ElasticSearchDataContext (NODE and TRANSPORT client) the REST client should be invalidated(throw an Exception).

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #22 

We POM dependency needs to be updated to 4.5  (when released)

### CODE REVIEW

**Comment by kaspersorensen** [comment]
Add also the SNAPSHOT upgrade to this PR, or else it does not make sense. And I think even it will also impose some other changes due to the fact that now a class cast has to happen when working with the DataContext.

File: src/main/java/org/datacleaner/extension/elasticsearch/ElasticSearchDocumentIdLookupTransformer.java [hunk 1]
```diff
@@ -70,11 +71,18 @@
 
     private UpdateableDatastoreConnection _connection;
 
+    @Validate
+    public void validate() {
+        if (elasticsearchDatastore.getClientType().equals(ElasticSearchDatastore.ClientType.REST)) {
```
Comment (kaspersorensen) [inline src/main/java/org/datacleaner/extension/elasticsearch/ElasticSearchDocumentIdLookupTransformer.java]: It would be better to check that it is either NODE or TRANSPORT here. I would formulate it as a switch statement. That way we cover the different scenarios instead of having a blacklist of 1. Should we potentially add more connection modes then this ```if``` would be stale.

File: src/main/java/org/datacleaner/extension/elasticsearch/ElasticSearchFullSearchTransformer.java [hunk 2]
```diff
@@ -75,6 +76,13 @@
     
     private UpdateableDatastoreConnection _connection;
     
+    @Validate
+    public void validate() {
+        if (elasticsearchDatastore.getClientType().equals(ElasticSearchDatastore.ClientType.REST)) {
```
Comment (kaspersorensen) [inline src/main/java/org/datacleaner/extension/elasticsearch/ElasticSearchFullSearchTransformer.java]: Same here

File: src/main/java/org/datacleaner/extension/elasticsearch/ElasticSearchIndexAnalyzer.java [hunk 3]
```diff
@@ -85,6 +86,13 @@
     private WriteBuffer _writeBuffer;
     private UpdateableDatastoreConnection _connection;
 
+    @Validate
+    public void validate() {
+        if (elasticsearchDatastore.getClientType().equals(ElasticSearchDatastore.ClientType.REST)) {
```
Comment (kaspersorensen) [inline src/main/java/org/datacleaner/extension/elasticsearch/ElasticSearchIndexAnalyzer.java]: and here :)

File: src/main/java/org/datacleaner/extension/elasticsearch/ElasticSearchTransformer.java [hunk 4]
```diff
@@ -25,4 +25,5 @@
 
     public static final String PROPERTY_ES_DATASTORE = "ElasticSearch index";
     public static final String PROPERTY_DOCUMENT_TYPE = "Document type";
+    public static final String CONNECTION_TYPE_ERROR = "This component requires the connection to ElasticSearch to be done as a NODE or via TRANSPORT protocol";
```
Comment (kaspersorensen) [inline src/main/java/org/datacleaner/extension/elasticsearch/ElasticSearchTransformer.java]: This is not really a part of the transformer's responsibility. I would rather create a new exception type with this text in it.

**Comment by ClaudiaPHI** [comment]
Changed per review. The cast to ElasticSearchDataContext was already been made because  The UpdateableDatastoreConnection class (which extends DatastoreConnection) getDataContext() method return a DataContext type, not an implementation

**Comment by kaspersorensen** [comment]
:+1:
